### ISSUE TITLE
GPU that returns Power [N/A] creates invalid JSON

### ISSUE THREAD

**Issue by antonywinn** [bigsk1/gpu-monitor#4]
If you have a GPU that does not return a power value (eg: N/A) stats are unavailable on the webpage.

I have a Quadro P620 on TrueNAS SCALE. With nvidia-smi it shows:

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.05             Driver Version: 550.127.05     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro P620                    Off |   00000000:41:00.0 Off |                  N/A |
| 34%   44C    P8             N/A /  N/A  |       3MiB /   2048MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

Current Stats JSON:

# cat gpu_current_stats.json
{
    "timestamp": "11-25 07:26:50",
    "temperature": 44,
    "utilization": 0,
    "memory": 3,
    "power": [N/A]
}

When viewing the page this error is viewable in the Developer Tools Network trace when that file is retrieved.
SyntaxError: JSON.parse: unexpected character at line 6 column 15 of the JSON data

Probable solution - quotes around N/A values: eg
{
    "timestamp": "11-25 07:26:50",
    "temperature": 44,
    "utilization": 0,
    "memory": 3,
    "power": "[N/A]"
}

Or default to zero, or "--" like other values.

**Comment by antonywinn** [comment]
@bigsk1 - thanks for taking a look at the issue. I have pulled the latest image, the graphing is working now (historical data) but the current stats display is still empty. 

Browser still shows an issue with gpu_current_stats.json

{
    "timestamp": "11-26 06:30:53",
    "temperature": 40,
    "utilization": 0,
    "memory": 3,
    "power": [N/A]     <---- doesn't like this.
}

**Comment by bigsk1** [comment]
@antonywinn ok it now handles both N/A and [N/A] power values and returns a 0, was able to test using `local gpu_stats="44, 0, 3, [N/A]"` and get back clean json from gpu_current_stats.json. 

Pull the latest image and should be good.

**Comment by antonywinn** [comment]
@bigsk1 - can confirm that dashboard is showing current data. Thank you.
